services:
  todoapp:
    image: todoapp:dev
    build:
      context: .
      dockerfile: src/ToDoApp/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development